export const cities = [
  {
    name: "Bucuresti",
    fromArray: [
      "Gara de Nord, Bucharest, Romania",
      "Aeroportul Internațional Henri Coandă (OTP), Calea Bucureştilor, Otopeni, Romania",
    ],
    toArray: [
      "Piața Unirii, Bucuresti",
      "Palatul Parlamentului, Bucuresti",
      "Piaţa Revoluţiei, Bucuresti",
      "Piaţa Arcul de Triumf, Bucuresti",
      "Gradina Japoneza, Bucuresti",
      "Muzeul National de Arta, Bucuresti",
      "Biserica Curtea Veche, Bucuresti",
      "Curtea Domnească, Bucuresti",
      "Muzeul Militar Național Regele Ferdinand I, Bucuresti",
      "JW Marriott Bucharest Grand Hotel, Bucuresti",
      "Patriarchal Cathedral, Bucuresti",
      "Stavropoleos Monastery, Bucuresti",
      "University Square, Bucuresti",
      "Cişmigiu Park, Bucuresti",
      "Herăstrău Park, Bucuresti",
      "Dimitrie Gusti National Village Museum in Bucharest, Bucuresti",
      "Palatul Cotroceni, Bucuresti",
      "Grădina Botanică, Bucuresti",
      "Piaţa Romană, Bucuresti",
      "Ibis Bucuresti Palatul Parlamentului, Bucuresti",
      "Parcul Carol, Bucuresti",
      "Casa Presei Libere, Bucuresti",
      "Muzeul George Enescu, Bucuresti",
      "National Museum of Art, Bucuresti",
      "Biserica Alba, Bucuresti",
      "Templul Coral, Bucuresti",
      "National Museum of Romanian History, Bucuresti",
      "Muzeul Naţional al Hărţilor şi Cărţii Vechi, Bucuresti",
      "Museum of the Romanian Peasant, Bucuresti",
      "Caru’ cu Bere (The Beer Chariot), Bucuresti",
      "Hanul lui Manuc (Manuc’s inn), Bucuresti",
      "Beraria H, Bucuresti",
      "Hard Rock Cafe, Bucuresti",
      "Downtown Bucharest Fountains, Bucuresti",
      "Cărturești Carousel Bookstore, Bucuresti",
      "Ateneul Roman, Bucuresti",
      "Centru Vechi, Bucuresti",
      "Otopeni, Bucuresti",
      "Obor, Bucuresti",
      "Afi Cotroceni, Bucuresti",
      "Park Lake, Bucuresti",
      "Promenada Mall, Bucuresti",
      "Sun Plaza, Bucuresti",
      "Baneasa Shopping City, Bucuresti",
      "Titan, Bucuresti",
      "Vitan, Bucuresti",
      "Berceni, Bucuresti",
      "Militari, Bucuresti",
    ],
  },
  {
    name: "Iași",
    fromArray: [
      "Gara Iași Nord, Piața Gării, Iași, Romania",
      "Aeroportul Internațional Iași, Iași Airport Heliport, Drumul Aeroportului, Iași, Romania",
    ],
    toArray: [
      'Universitatea "Alexandru Ioan Cuza" - Corp A, Iași',
      "Biblioteca Centrala Universitara Mihai Eminescu, Iași",
      "Bojdeuca Ion Creangă, Iași",
      "Casa Dosoftei, Iași",
      "Muzeul Literaturii Române - Casa Pogor, Iași",
      "Catedrala Mitropolitană, Iași",
      "Grădina Botanică Anastasie Fătu, Iași",
      "Mănăstirea Cetăţuia, Iași",
      "Mănăstirea Frumoasa, Iași",
      "Mânăstirea Galata, Iași",
      "Manastirea Golia, Iași",
      "Biserica Sfintii Trei Ierarhi, Iași",
      "Muzeul de Istorie Naturala, Iași",
      "Muzeul Unirii, Iași",
      "Muzeul Mihai Eminescu, Iași",
      "Palatul Culturii, Iași",
      "Palatul Roznavanu(Primaria), Iași",
      "Parcul Copou, Iași",
      "Muzeul Literaturii Române - Casa Pogor, Iași",
      'Teatrul National "Vasile Alecsandri", Iași',
      "Muzeul Teatrului, Iași",
      "Muzeul Petru Poni, Iași",
      "Casa Memoriala Otilia Cazimir, Iași",
      "Ruinele curtii domnesti, Iași",
      "Aeroportul Internațional Iași, Iași",
      "Toujours, Iași",
      "Vivo Fusion Food Bar, Iași",
      "Romeo e Giulietta Pizzeria Restaurant, Iași",
      "Blue Acqua Restaurant - Iasi, Iași",
      "Mamma Mia Restaurant & Catering, Iași",
      "Fenice Palas, Iași",
      "Andalu GastroBar, Iași",
      "Tiki Bistro, Iași",
      "Restaurant Oscar, Iași",
      "Cuib, Iași",
      "Panoramic Restaurant, Iași",
      "Restaurant Tirol, Iași",
      "Buena Vista, Iași",
      "Krud Restaurant & Braserie, Iași",
      "Hotel International Iasi, Iași",
      "Unirea Hotel & SPA, Iași",
      "Pleiada Boutique Hotel, Iași",
      "Hotel Select Iasi, Iași",
      "Ramada by Wyndham Iasi City Centre, Iași",
      "Hotel Arnia, Iași",
      "Motel Bucium, Iași",
      "Grand Hotel Traian, Iași",
      "Hampton by Hilton Iasi, Iași",
      "Continental Hotel, Iași",
      "Gara Iasi, Iași",
    ],
  },
  {
    name: "Cluj-Napoca",
    fromArray: [
      "Gara Cluj-Napoca, Strada Piața Gării, Cluj-Napoca, Romania",
      "Aeroportul Internațional Avram Iancu Cluj-Napoca (CLJ), Strada Traian Vuia, Cluj-Napoca, Romania",
    ],
    toArray: [
      "Piata Unirii, Cluj-Napoca",
      "Universitatea Babes Bolyai, Cluj-Napoca",
      "Statuia Avram Iancu, Cluj-Napoca",
      "Liceul Emil Racovita, Cluj-Napoca",
      "Piata Cipariu, Cluj-Napoca",
      "Piata Mihai Viteazu, Cluj-Napoca",
      "Gara CFR, Cluj-Napoca",
      "Facultatea de Litere, Cluj-Napoca",
      "Hotel Belvedere, Cluj-Napoca",
      "Stadionul Moina, Cluj-Napoca",
      "Cazino, Cluj-Napoca",
      "Teatrul National, Cluj-Napoca",
      "Hala Agroalimentara, Cluj-Napoca",
      "Aeroportul Internațional Avram Iancu Cluj, Cluj-Napoca",
      "Gradina Botanica - Serele, Cluj-Napoca",
      "Gradina japoneza, Cluj-Napoca",
      "Biserica Reformata pe Kogalniceanu, Cluj-Napoca",
      "Catedrala Calvaria, Cluj-Napoca",
      "Bastionul Croitorilor, Cluj-Napoca",
      "Catedrala Ortodoxa, Cluj-Napoca",
      "Biblioteca Centrala Universitara, Cluj-Napoca",
      "Palatul Banffy, Cluj-Napoca",
      "Biserica Schimbarea la Fata, Cluj-Napoca",
      "Palatul Arhiepiscopiei Ortodoxe, Cluj-Napoca",
      "Palatul Szeky, Cluj-Napoca",
      "Biserica Sf. Petru si Pavel, Cluj-Napoca",
      "Biserica Bob, Cluj-Napoca",
      "Biserica cu Cocos, Cluj-Napoca",
      "Biserica Evanghelica Luterana, Cluj-Napoca",
      "Biserica Franciscana, Cluj-Napoca",
      "Biserica Piaristilor, Cluj-Napoca",
      "Biserica Reformata Doua Turnuri, Cluj-Napoca",
      "Palatul de Finante, Cluj-Napoca",
      "Statuia Sf.Gheorghe, Cluj-Napoca",
      "Obeliscul Carolina, Cluj-Napoca",
      "Statuia Lupoaicei, Cluj-Napoca",
      "Palatul de Justitie, Cluj-Napoca",
      "Statuia Matei Corvin, Cluj-Napoca",
      "Colegiul George Cosbuc, Cluj-Napoca",
      "Facultatea de Chimie, Cluj-Napoca",
      "Sinagoga, Cluj-Napoca",
      "Camera de Comert si Industrie, Cluj-Napoca",
      "Magazin Central, Cluj-Napoca",
      "Monumentul Memorandistilor, Cluj-Napoca",
      "Cetatuia, Cluj-Napoca",
      "Hotel Victoria, Cluj-Napoca",
      "Hotel Melody, Cluj-Napoca",
      "Biblioteca Academiei, Cluj-Napoca",
      "Biserica Sf. Mihail, Cluj-Napoca",
      "Gara Cluj-Napoca, Cluj-Napoca",
    ],
  },
  {
    name: "Timișoara",
    fromArray: [
      "Aeroportul Internațional Avram Iancu Cluj-Napoca (CLJ), Strada Traian Vuia, Cluj-Napoca, Romania",
      "Timișoara International Airport, Strada Aeroportului, Timișoara, Romania",
    ],
    toArray: [
      "Gara Timișoara Nord, Timișoara",
      'Aeroportul Internațional "Traian Vuia" Timişoara, Timișoara',
      "Banat Village Museum, Timișoara",
      "Sinagoga Evreiasca, Strada Mărășești, Timișoara",
      "Orthodox Cathedral, Timișoara",
      "Piaţa Libertăţii (Liberty Square), Timișoara",
      "Piața Unirii (Union Square), Timișoara",
      "Roman Catholic Cathedral of Saint George, Timișoara",
      "Sfânta Treime Statue, Timișoara",
      "House of Lions, Timișoara",
      "Brück House, Timișoara",
      "Baroque Palace, Timișoara",
      "Timisoara Art Museum, Timișoara",
      "Cardinal Point Fountain, Timișoara",
      "Maria Theresia Bastion, Timișoara",
      "Ceasul Floral, Timișoara",
      "Copacul breslelor, Strada Proclamația de la Timișoara, Timișoara",
      "National Opera House, Timișoara",
      "Lloyd Palace, Timișoara",
      "Huniade Castle, Timișoara",
      "Parcul Rozelor, Timișoara",
      "Cathedral Park, Timișoara",
      "Iulius Gardens, Timișoara",
      "Central Park, Timișoara",
      "NH Timisoara, Timișoara",
      "Timisoara Hotel, Timișoara",
      "Boutique Hotel Casa del Sole, Timișoara",
      "Hotel Savoy, Timișoara",
      "Mercure Timisoara, Timișoara",
      "Del Corso Hotel, Timișoara",
      "ibis Timisoara City Center Hotel, Timișoara",
      "North Star Continental Resort, Timișoara",
      "Hotel Galaxy, Timișoara",
      "Hotel Reghina Blue, Timișoara",
      "Restaurant Tinecz, Timișoara",
      "Vinto, Timișoara",
      "La Calul Alb, Timișoara",
      "Restaurant Sabres, Timișoara",
      "Le Monelline, Timișoara",
      "Neata Omelette Bistro, Timișoara",
      "Restaurant Merlot, Timișoara",
      "Little Hanoi, Timișoara",
      "Biofresh Restaurant Vegetarian and Vegan, Timișoara",
      "Grill to Chill, Timișoara",
      "Casa Bunicii 1, Timișoara",
      "Cafeneaua Verde, Timișoara",
      "Iulius Town, Timișoara",
      "Shopping City Timișoara, Timișoara",
      "Bega Shopping Center, Timișoara",
      "Parcul Copiilor Ion Creangă, Timișoara",
    ],
  },
  {
    name: "Constanța",
    fromArray: [
      "Gara, Constanța, Romania",
      "Mihail Kogălniceanu International Airport, Strada Tudor Vladimirescu, Romania",
    ],
    toArray: [
      "Aeroportul Internațional Mihail Kogălniceanu Constanța, Constanța",
      "Gara Constanța, Constanța",
      "Constanța Dolphinarium, Constanța",
      "Statuia lui Ovidiu din Constanța, Constanța",
      "Faleza Municipiului Constanța, Constanța",
      "Parcul Gării, Constanța",
      "Muzeul de artă Constanța, Constanța",
      "Muzeul de Sculptură Ion Jalea, Constanța",
      "Muzeul de Istorie Națională și Arheologie din Constanța, Constanța",
      "Catedrala Sfinții Apostoli Petru și Pavel, Constanța",
      "Muzeul de artă populară, Constanța",
      "Gravity Park, Constanța",
      "Lupa Capitolina Tomis, Constanța",
      "Promenada Mamaia, Constanța",
      "Microrezervație, Constanța",
      "Mamaia beach, Constanța",
      "Muzeul Marinei Române, Constanța",
      "Plaja Modern, Constanța",
      "Luna ParkVacanța, Constanța",
      "Marea Moschee din Constanța, Constanța",
      "Parcul Carol I, Constanța",
      "Băile Romane ruine, Constanța",
      "Termele Romane, Constanța",
      "Farul Genovez, Constanța",
      "Cazino Constanta, Constanța",
      "IAKI Conference & Spa Hotel, Constanța",
      "Splendid Conference & Spa Hotel, Constanța",
      "Vega Hotel, Constanța",
      "New Splendid Hotel & Spa, Constanța",
      "Hotel Cherica, Constanța",
      "Aqvatonic Hotel - Steaua de Mare, Constanța",
      "Hotel Dali, Constanța",
      "Marina Regia Residence, Constanța",
      "Hotel Carol, Constanța",
      "Hotel On Plonge Jr., Constanța",
      "IRISH PUB, Constanța",
      "Nikos Greek Taverna, Constanța",
      "Tara's GastroPub, Constanța",
      "Marco Polo, Constanța",
      "Bacaro Port, Constanța",
      "Restaurant Chevalet, Constanța",
      "dasKino, Constanța",
      "Blue Acqua Restaurant - Faleza Mamaia, Constanța",
      "Reyna, Constanța",
      "Toscana, Constanța",
      "City Park Mall, Constanța",
      "VIVO!, Constanța",
      "Tomis Mall, Constanța",
      "Portul Turistic Tomis, Constanța",
      "Farul Verde Port Turistic Tomis, Constanța",
    ],
  },
  {
    name: "Craiova",
    fromArray: [
      "Gara Craiova, Piața Constantin Brâncuși, Craiova, Romania",
      "Aeroportul Internațional Craiova, Calea București, Craiova, Romania",
    ],
    toArray: [
      "Aeroportul Internațional Craiova, Craiova",
      "Gara Craiova, Craiova",
      "Parcul Nicolae Romanescu, Craiova",
      "Craiova's Art Museum, Craiova",
      "Grădina Botanică Craiova (Botanical Garden), Craiova",
      "Piața Mihai Viteazul, Craiova",
      "Casa Baniei, Craiova",
      "Minerva Hotel & Casino, Craiova",
      "Muzeul Stiintele Naturii Oltenia, Craiova",
      "Electroputere Mall, Craiova",
      "Muzeul Olteniei, Craiova",
      "Metropolitan Cathedral of St Demetrius, Craiova",
      "Filarmonica Oltenia, Craiova",
      "Ion Oblemenco Stadium, Craiova",
      "Craiova Musical Fountain, Craiova",
      "Parcul Tineretului, Bulevardul Știrbei Vodă, Craiova",
      "Sala Polivalenta Craiova, Craiova",
      "Craiova Water Park, Craiova",
      "Biserica Mantuleasa, Craiova",
      "Million Casino, Craiova",
      "Fantana Purcarului, Craiova",
      "Cimitirul Ungureni, Craiova",
      "Biserica Madona Dudu, Craiova",
      "Piscina Spa Magic Land, Craiova",
      "Tenis Club Lucian Craiova, Craiova",
      "Zodiac Sala Jocuri Craiova, Craiova",
      "Ramada Plaza Craiova, Craiova",
      "Hotel Splendid, Craiova",
      "Hotel Royal Craiova, Craiova",
      "Prestige Boutique Hotel Craiova, Craiova",
      "Hotel Golden House, Craiova",
      "Hotel Boutique 5 Continents, Craiova",
      "La Rocca Hotel Boutique, Craiova",
      "Bruxelles Guesthouse Craiova, Craiova",
      "Alfredo Hostel, Craiova",
      "Hotel Rexton, Craiova",
      "The Manor Restaurant & Lounge, Craiova",
      "Craft, Craiova",
      "Pizzeria Trevi, Craiova",
      "Iberico, Craiova",
      "Trattoria Il Calcio, Craiova",
      "Big Ben, Craiova",
      "al'Zaatar, Craiova",
      "Casa Ghincea, Craiova",
      "Epoca Steak House & Wine Bar, Craiova",
      "Bulevard Restaurant, Craiova",
      "Electroputere Parc, Craiova",
      "Centru vechi Craiova, Craiova",
      "Fajitas Tex Mex, Craiova",
      "Artizan35, Craiova",
    ],
  },
  {
    name: "Brașov",
    fromArray: ["Gara Brasov, Bulevardul Gării, Brașov, Romania"],
    toArray: [
      "Gara Brașov, Brașov",
      "Casa Sfatului, Brașov",
      "Casa Muresenilor, Brașov",
      "Bastionul Tesatorilor, Brașov",
      "Muzeul de Arta, Brașov",
      "Biblioteca Judeteana, Brașov",
      "Okian, Strada Mureșenilor, Brașov",
      "Biserica Neagra, Brașov",
      "Aeroportul Brașov, Brașov",
      "Rectoratul Universitatii Transilvania, Brașov",
      "Centrul Cultural Reduta, Brașov",
      "Casa Baiulescu, Brașov",
      "Libraria St. O. Iosif, Brașov",
      "Cantina Memo = Casa de Cultura a Studentilor, Brașov",
      "Colina Universitatii, Brașov",
      "Musik Cafe, Brașov",
      "Casa Medievala, Brașov",
      'Teatrul Dramatic "Sica Alexandrescu", Brașov',
      "Paris Esthetique 5 Brașov",
      "Cetatuia Brasov, Brașov",
      "Biserica Evanghelica Sf. Bartolomeu, Brașov",
      "Turnul Negru, Brașov",
      "Turnul Alb, Brașov",
      "Bastionul Graft, Brașov",
      "Cafeneaua Graft, Brașov",
      "Biserica Franciscana Sf. Ioan, Brașov",
      'Muzeul "Prima Scoala Romaneasca", Brașov',
      "Biserica Ortodoxa Sf. Nicolae, Brașov",
      "Sinagoga, Brașov",
      "Muzeul de Etnografie, Brașov",
      "Biserica Romano-Catolica Sf. Petru si Pavel, Brașov",
      "Opera Brasov, Brașov",
      "AGHO Cocktail Studio, Brasov",
      "Varful Tampa, Brașov",
      "Kronwell Brasov Hotel, Brașov",
      "Belfort Hotel, Brașov",
      "Bella Muzica, Brașov",
      "Hotel Casa Wagner, Brașov",
      "QOSMO Brasov Hotel, Brașov",
      "Armatti Hotel, Brașov",
      "Hotel Aro Palace, Brașov",
      "Ograda, Brașov",
      "Cucinino Pasta & Pizza, Brașov",
      "La Ceaun - Piata Sfatului, Brașov",
      "Casa Hirscher, Brașov",
      "Coresi Shopping Resort, Brașov",
      "Unirea Shopping Center Brașov, Brașov",
    ],
  },
  {
    name: "Galați",
    fromArray: ["Gara Galați, Strada Gării, Galați, Romania"],
    toArray: [
      "Gara Galați, Galați",
      "Complexul Muzeal de Științele Naturii Răsvan Angheluță Galați",
      "Paul Păltânea History Museum of Galați, Galați",
      "Catedrala Galati, Galați",
      "Turnul Televiziunii, Galați",
      "Manastirea Vladimiresti, Galați",
      "Gradina Publica, Galați",
      "House of body, Galați",
      "Brain Games, Galați",
      "Exit Escape Room, Galați",
      "Mercure Galati Centrum, Galați",
      "Vila Belvedere, Galați",
      "Faleza Hotel by Vega, Galați",
      "Hotel Bordeaux, Galați",
      "Jolie Apartments, Galați",
      "Hotel Vega, Galați",
      "Ibis Styles Dunarea Galati, Galați",
      "Magnus Hotel, Galați",
      "Hotel Riverside, Galați",
      "Hotel Alex, Galați",
      "Blue Acqua Restaurant - Faleza Dunarii Galati, Galați",
      "Teatris Restaurant - Parc Eminescu Galati, Galați",
      "STAGE- Nice Dining, Galați",
      "Gossip Cafe, Galați",
      "Union Jack, Galați",
      "C House Lounge Cafe Galati, Galați",
      "Dulce by Paula, Galați",
      "Casa Gustului, Galați",
      "Amadeus, Galați",
      "Casa Corso, Galați",
      "Craft - Rebel Food, Galați",
      "Tapas Bar Galati, Galați",
      "Restaurant Lyra, Galați",
      "Alex Restaurant, Galați",
      "Shopping City Galati, Galați",
      "Dunărea mall, Galați",
      "Port Galați, Galați",
      "Parcul C.F.R., Galați",
      "Rezervația și Grădina Zoologică Gârboavele, Galați",
      "Vintage Pub Galati, Galați",
      "The Docks Pub Galați, Galați",
      "Versus Pub, Galați",
      "Delirium Pub, Galați",
      "The Clock Museum, Galați",
    ],
  },
  {
    name: "Ploiești",
    fromArray: ["Gara Ploiești Sud, Strada Depoului, Ploiești, Romania"],
    toArray: [
      "Ion Luca Caragiale Museum, Ploiești",
      "Cathedral of Ploiesti, Ploiești",
      "Muzeul judetean de stiintele naturii prahova, Ploiești",
      "Marea Sinagoga, Ploiești",
      "County Museum of History and Archeology, Ploiești",
      "Parcul Bucov, Ploiești",
      "Teatrul Toma Caragiu, Ploiești",
      "MUZEUL MEMORIAL CONSTANTIN STERE, Ploiesti",
      "Zoo Ploiesti, Ploiești",
      "Gara Ploiești Sud, Ploiești",
      "Ploiești Shopping City, Ploiești",
      "AFI Ploiești, Ploiești",
      "Prahova Value Centre, Ploiești",
      "Hotel Central, Ploiești",
      "Sky Blue Hotel & Spa, Ploiești",
      "Hotel Forum Ploiesti, Ploiești",
      "Albert Hotel, Ploiești",
      "Acapulco Hotel, Ploiești",
      "Vigo Hotel, Ploiești",
      "Prahova Plaza Hotel, Ploiești",
      "Lacul Verde Resort, Ploiești",
      "Vigo Grand Hotel, Ploiești",
      "Vila Romeo and Juliet, Ploiești",
      "Hotel Angelo d'Oro, Ploiești",
      "Hotel Maryo, Ploiești",
      "Hotel City Ploiesti, Ploiești",
      "Complex Europa L.G., Ploiești",
      "Villa Bijoux, Ploiești",
      "Casa Timis, Ploiești",
      "Yarus Hotel, Ploiești",
      "Pensiunea Casa Simoni, Ploiești",
      "Restaurant Terraverde, Ploiești",
      "Taverna Greceasca Dionysos, Ploiești",
      "DOMA Urban Bistro, Ploiești",
      "Longline Specialty Coffee, Ploiești",
      "Hanul Dacilor, Ploiești",
      "Akua Garden Restaurant, Ploiești",
      "Cafeneaua Natiei, Ploiești",
      "Restaurant Prestij, Ploiești",
      "Caffe Milano, Ploiești",
      "Restaurant DaVinci, Ploiești",
      "Vienna Cafe, Ploiești",
      "Curtea Berarilor Timisoreana Ploiesti, Ploiești",
      "The Fable, Ploiești",
      "Restaurantul & Pub London House, Ploiești",
      "Bulevard Pub OK, Ploiești",
      "Tres Olivos - Rahovei, Ploiești",
      "KS Pub, Ploiești",
      "Aleppo Coffee & Drinks, Ploiești",
    ],
  },
  {
    name: "Oradea",
    fromArray: [
      "Gara Oradea, Piața București, Oradea, Romania",
      "Aeroportul Internaţional Oradea, Calea Aradului, Oradea, Romania",
    ],
    toArray: [
      "Restaurant Ciuperca, Oradea",
      "Roman Catholic Cathedral, Oradea",
      "Piața Unirii, Oradea",
      "Black Eagle Palace, Oradea",
      "Palatul Deutsch K. I., Oradea",
      "Ice-Cafe Roze, Oradea",
      "Sinagoga Ortodoxă, Oradea",
      "Catedrala Adormirea Maicii Domnului, Oradea",
      "St. Nicholas Cathedral, Oradea",
      "Liceul Greco-Catolic Iuliu Maniu, Oradea",
      "Palace of Greek - Catholic Bishopric, Oradea",
      "Oradea Town Hall, Oradea",
      "Promenadă Crișul Repede, Oradea",
      "Oradea Shopping City, Oradea",
      "Oradea Plaza, Oradea",
      "Era Shopping Park, Oradea",
      "Lotus Retail Park, Oradea",
      "Centrul Comercial Crișul, Oradea",
      "Gara Oradea, Oradea",
      "Ramada by Wyndham Oradea, Oradea",
      "DoubleTree by Hilton Hotel Oradea, Oradea",
      "Continental Forum Oradea, Oradea",
      "Hotel Astoria Oradea, Oradea",
      "Sky Hotel Oradea, Oradea",
      "Hotel Maxim, Oradea",
      "Ivana Apart Hotel, Oradea",
      "Hotel Impero, Oradea",
      "Avalon Rooms, Oradea",
      "Silver Hotel Conference & Spa, Oradea",
      "Hotel Iris, Oradea",
      "Elite Resort Hotel, Oradea",
      "Hotel Nevis Wellness & SPA, Oradea",
      "Oradea Central Hostel, Oradea",
      "Stokker Hotel, Oradea",
      "Piata9, Oradea",
      "Via29, Oradea",
      "Graf Restaurant & Pizzerie, Oradea",
      "Steak HUB, Oradea",
      "Rivo Restaurant & Lounge, Oradea",
      "London Brothers Oradea, Oradea",
      "Baraw, Oradea",
      "To Chefs Restaurant, Oradea",
      "Restaurant Allegria, Oradea",
      "Meridian Zero, Oradea",
      "ReWine Bistro, Oradea",
      "The Dripper, Oradea",
      "Restaurant ROSECAS, Oradea",
      "Hanul cu Noroc, Oradea",
      "XO Restaurant, Oradea",
      "Crinul Alb - Restaurant & Pizzeria, Oradea",
    ],
  },
  {
    name: "Brăila",
    fromArray: ["Gara Brăila, Strada General Eremia Grigorescu, Brăila, Romania"],
    toArray: [
      "Gara Braila, Brăila",
      "Maria Filotti Theatre, Brăila",
      "Ceasul public din Brăila",
      "Braila Mall, Brăila",
      "Nicăpetre Cultural Centre, Brăila",
      "Catedrala Nasterea Domnului, Brăila",
      "Muzeul Brailei, Brăila",
      "Ferma De La Coada, Brăila",
      "Fântâna Cinetică, Brăila",
      "Parcul Monument Brăila, Brăila",
      "Grădina Publică/Grădina Mare Brăila, Brăila",
      "Parcul Bulevard, Brăila",
      "Faleza Braila, Brăila",
      "Grand Hotel Orient, Brăila",
      "Hotel Saint-Germain, Brăila",
      "Residenza Dutzu, Brăila",
      "Hotel Triumph, Brăila",
      "Hotel LMS, Brăila",
      "Hotel Traian Braila, Brăila",
      "Nemo, Brăila",
      "Hotel Belvedere Braila, Brăila",
      "Hotel Orient, Brăila",
      "Old Fane's Lodge, Brăila",
      "Hotel Rebis, Brăila",
      "Bella Italia Braila, Brăila",
      "Pensiunea Reset Club, Brăila",
      "Pensiune Heavens, Brăila",
      "Porto Franco Residence, Brăila",
      "Hotel Paris Braila, Brăila",
      "Hotel Edy's Royal, Brăila",
      "Alma Health & Spa Retreat, Brăila",
      "Sunrise Marina - Wine Bistro, Brăila",
      "Restaurant Carol, Brăila",
      "Casa Domneasca, Brăila",
      "La Fenice Restaurant, Brăila",
      "Peste Si Vin, Brăila",
      "Reset Irish Pub, Brăila",
      "Residenza Dutzu Restaurant, Brăila",
      "Pomodoro Restaurant, Brăila",
      "Restaurant AMUSE, Brăila",
      "Thassos Food, Brăila",
      "Anotimpuri, Brăila",
      "R Caffee, Brăila",
      "Cabana Stejarilor, Brăila",
      "All Saints, Brăila",
      "Taboo Doner - Braila Calea Calarasilor, Brăila",
      "Terasa Imperial Braila, Brăila",
      "Restaurant Continental, Brăila",
      "Trei Randunici, Brăila",
    ],
  },
  {
    name: "Pitești",
    fromArray: ["Gara Piteşti, Bulevardul Republicii, Pitești, Romania"],
    toArray: [
      "Gara Pitești, Pitești",
      "Pitesti Prison Memorial, Pitești",
      "Fântâna Muzicală, Pitești",
      "Complex Sportiv Comesad, Pitești",
      "Biserica Sfânta Vineri, Pitești",
      "Trivale Park, Pitești",
      "Muzeul Judetean Arges, Pitești",
      "Biserica Sfintele Femei Mironosite, Pitești",
      "Galeria de Arta Pitesti, Pitești",
      "Vechea Vatra, Pitești",
      "VIVO! Mall, Pitești",
      "Vipoker Club, Pitești",
      "Million Casino Pitesti, Pitești",
      "Hint Escape Rooms, Pitești",
      "Laser Tag Pitesti, Pitești",
      "Gradina Zoologica Pitesti, Pitești",
      "Everest Spa & Beauty, Pitești",
      "Trivale Cinema, Pitești",
      "Planetarium Piteşti, Pitești",
      "Vinoteca Trivale, Pitești",
      "Fundatia Culturala Ilfoveanu, Pitești",
      "Cinema City Pitesti, Pitești",
      "Urban Home, Pitești",
      "Meadow Park Argesului, Pitești",
      "Victoria Spa, Pitești",
      "Ramada Pitesti, Pitești",
      "La Strada Boutique Villa, Pitești",
      "Hotel Arges, Pitești",
      "Victoria Hotel, Pitești",
      "Casa Maria Arges, Pitești",
      "Pensiunea Cora, Pitești",
      "Casa Teilor, Pitești",
      "Hotel Duet, Pitești",
      "Hotel Magic Trivale, Pitești",
      "Pensiune Pavo, Pitești",
      "Celly Hotel, Pitești",
      "Hotel Grandis Apulum, Pitești",
      "Bistro 27, Pitești",
      "La Tuciuri, Pitești",
      "Casa Argeseana, Pitești",
      "Casa Sattler, Pitești",
      "La Dolce Vita, Pitești",
      "Trattoria by Garden Pub, Pitești",
      "La Strada Pub & Restaurant, Pitești",
      "Zahana, Pitești",
      "Restaurant Conti, Pitești",
      "Kells Craft Beer, Pitești",
    ],
  },
  {
    name: "Arad",
    fromArray: ["Gara Arad, Piața Gării, Arad, Romania", "Arad International Airport, Aleea Aeroport, Arad, Romania"],
    toArray: [
      "Aeroportul Internațional Arad, Arad",
      "Gara Arad, Arad",
      "Cetatea Aradului, Arad",
      "Biserica franciscană, Arad",
      "Podul Traian, Arad",
      "Colegiul Naţional “Moise Nicoară”, Arad",
      "Palatul parohiei Evanghelice-Lutherane",
      "Palatul Bohuş, Arad",
      "Clădirea Diecezanei, Arad",
      "Palatul Neumann, Arad",
      "Palatul Szántay, Arad",
      "Palatul Cultural Arad, Arad",
      "Filarmonica de Stat, Arad",
      "Teatrul de Stat “Ion Slavici”, Arad",
      "Palatul Kovács, Arad",
      "Hotelul Ardealul (Crucea Albă), Arad",
      "Biserica evanghelică luterană, Arad",
      "Palatul Andrényi, Palatul Copiilor, Arad",
      "Palatul Băncii Naţionale, Arad",
      "Biserica romano-catolică Aradu Nou, Arad",
      "Casa Cu Lacăt şi Trunchi, Arad",
      "Sinagoga neologă (de rit mozaic), Arad",
      "Palatul Administraţiei Financiare (Trezoreria), Arad",
      "Holy Trinity Cathedral, Arad",
      "City Hall, Arad",
      "Biserica Catolică Sf. Anton de Padova revolutiei",
      "Atrium Mall, Arad",
      "Galleria, Arad",
      "Retail Park Arad, Arad",
      "Ibis Styles Arad, Arad",
      "Continental Forum Arad, Arad",
      "Hotel Coandi, Arad",
      "Hotel Leon & Spa, Arad",
      "Best Western Central Hotel, Arad",
      "Grant Boutique Hotel, Arad",
      "Pensiune Roua, Arad",
      "Nimbus, Arad",
      "Pensiunea Johanna, Arad",
      "Ema Del Mar Arad, Arad",
      "Ristorante Picasso, Arad",
      "Euphoria Biergarten Arad, Arad",
      "Restaurant Libanez, Arad",
      "Grenier Brasserie, Arad",
      "Restaurant Il Classico - Arad, Arad",
      "Pizzerie Restaurant DON, Arad",
      "Taverna Pecicana, Arad",
      "Restaurant Ratio, Arad",
    ],
  },
  {
    name: "Suceava",
    fromArray: [
      "Gara Suceava, Strada Nicolae Iorga, Suceava, Romania",
      "Aeroportul Internațional Ștefan cel Mare Suceava, Orașul Salcea, Romania",
    ],
    toArray: [
      "Aeroportul International Stefan cel Mare, Suceava",
      "Gara Suceava, Suceava",
      "Fortress of Suceava, Suceava",
      "Cacica Salt Mine, Suceava",
      "Muzeul Satului Bucovinean (Bukovina Village Museum), Suceava",
      "Mănăstirea Sfântul Ioan cel Nou, Suceava",
      "Planetariul din Suceava, Suceava",
      "Mănăstirea Zamca, Suceava",
      "Muzeul de Istorie, Suceava",
      "Biserica Mirăuți, Suceava",
      "Hanul Domnesc, Suceava",
      "Muzeul de Științele Naturii, Suceava",
      "Curtea Domnească, Suceava",
      "Gah Syngogue, Suceava",
      "Iulius Mall Suceava, Suceava",
      "Shopping City, Suceava",
      "Hotel Sonnenhof, Suceava",
      "Mandachi Hotel & Spa, Suceava",
      "Continental Suceava, Suceava",
      "Villa Alice, Suceava",
      "Hotel Residenz, Suceava",
      "Hotel Balada, Suceava",
      "Pensiunea Santa Fe, Suceava",
      "Lary Hostel, Suceava",
      "Casa Bucovineana, Suceava",
      "Agropensiunea Ioana, Suceava",
      "Hotel Bucovina, Suceava",
      "Rapsodia Pension, Suceava",
      "Casa de Oaspeti Suceava, Suceava",
      "Hotel Orizont Suceava, Suceava",
      "Coliba Haiducilor Bucovina, Suceava",
      "Hotel Polaris, Suceava",
      "Restaurant Latino, Suceava",
      "Restaurant Mosaik, Suceava",
      "Eker, Suceava",
      "Zona, Suceava",
      "Pepper Grill'n Chill, Suceava",
      "Pepenero, Suceava",
      "Apropo Cafe, Suceava",
      "Urban Street Food & Bar, Suceava",
      "Casa Bucovineana Restaurant, Suceava",
      "Restaurant Santa Fe, Suceava",
      "Nevada Pizza and Burger House, Suceava",
      "Bazzil Restaurant, Suceava",
      "Sempre Pizza, Suceava",
      "Container Street Food, Suceava",
      "Restaurant Balada, Suceava",
      "BIZZ Cafe, Suceava",
    ],
  },
  {
    name: "Bacău",
    fromArray: [
      "Gara Bacău, Strada Gării, Bacău, Romania",
      "George Enescu International Airport, Strada Aeroportului, Bacău, Romania",
    ],
    toArray: [
      "Aeroportul Internațional George Enescu, Bacău",
      "Gara Bacău, Bacău",
      "Biserica Precista, Bacău",
      "Arena Mall Bacau, Bacău",
      "Observatorul Astronomic Victor Anestin, Bacău",
      "Gepex Park, Bacău",
      "Principe, Bacău",
      "Hotel Dumbrava, Bacău",
      "Helen Hotel Bacau, Bacău",
      "Hotel Bohemia, Bacău",
      "Podu' cu lanturi, Bacău",
      "Piazzetta Boutique Hotel & Restaurant, Bacău",
      "Vila Tosca, Bacău",
      "Boutique Hotel Bizant, Bacău",
      "Pensiunea Elite, Bacău",
      "President Hotel Bacau, Bacău",
      "Pensiunea Rebeca Palanca, Bacău",
      "Hotel Ellero, Bacău",
      "Snobbish Burger, Bacău",
      "La Excelentza, Bacău",
      "Decebal Hotel, Bacău",
      "Boutique Tosca Regal, Bacău",
      "Pensiunea Vila Royal, Bacău",
      "Villa AnnaLia, Bacău",
      "Pensiunea Moldavia, Bacău",
      "C&C Residence Hotel, Bacău",
      "Pensiunea Daciana, Bacău",
      "Club Karo, Bacău",
      "AntikHaus, Bacău",
      "La Bettola, Bacău",
      "Gran Gourmet Ristorante, Bacău",
      "Bacchus Bistro Chic, Bacău",
      "Lake House, Bacău",
      "La Taverna Hotel Helen, Bacău",
      "Restaurant Savarin, Bacău",
      "Hanovra, Bacău",
      "Twomey's Irish Pub, Bacău",
      "Casa Rebeca, Bacău",
      "Restaurant Vatra, Bacău",
      "Green Park, Bacău",
      "Osteria Roma, Bacău",
      "BERARIA VALHALLA, Bacău",
      "Pizzeria Luca, Bacău",
      "La Bettola Del Parco, Bacău",
      "Dom Bistro & Lounge, Bacău",
      "Miorita, Bacău",
      "Mau Cafe, Bacău",
      "Unirii street, Bacău",
    ],
  },
  {
    name: "Târgu Mureș",
    fromArray: [
      "Gara Târgu Mureș, Strada Sârguinței, Craiova, Romania",
      "Târgu Mureș Transilvania Airport, DN15, Ungheni, Romania",
    ],
    toArray: [
      "Aeroportul Internațional Transilvania din Târgu Mureș, Târgu Mureș",
      "Gara Târgu Mureș, Târgu Mureș",
      "Culture Palace, Târgu Mureș",
      "Ethnographic Museum, Târgu Mureș",
      "Consiliul Județean Mureș, Piața Victoriei, Târgu Mureș",
      "Targu Mures Fortress, Târgu Mureș",
      "Orthodox Cathedral, Târgu Mureș",
      "Teleki-Bolyai Library, Târgu Mureș",
      "Orthodox Synagogue, Târgu Mureș",
      "Complexul Weekend, Târgu Mureș",
      "Greco-Catholic Cathedral, Târgu Mureș",
      "Fortress Church, Târgu Mureș",
      "Roman Catholic Church, Târgu Mureș",
      "City Museum, Târgu Mureș",
      "Teleki House, Târgu Mureș",
      "La Gradina Zoo, Târgu Mureș",
      "Petry Museum, Târgu Mureș",
      "Mureș Mall, Târgu Mureș",
      "Shopping City, Târgu Mureș",
      "Promenada Mall, Târgu Mureș",
      "Hotel PRIVO, Târgu Mureș",
      "Plaza V Executive Hotel, Târgu Mureș",
      "Business Hotel, Târgu Mureș",
      "Pensiunea Select Central, Târgu Mureș",
      "Hotel Tempo, Târgu Mureș",
      "Pensiunea Imperial, Târgu Mureș",
      "Continental Forum Tirgu Mures, Târgu Mureș",
      "Haller Boutique, Târgu Mureș",
      "Curtea Bavareza, Târgu Mureș",
      "Pension Tempo, Târgu Mureș",
      "Hotel Concordia, Târgu Mureș",
      "Villa Helvetia, Târgu Mureș",
      "Pensiunea Cleopatra, Târgu Mureș",
      "Imperial Inn, Târgu Mureș",
      "Pensiunea El Passo, Târgu Mureș",
      "Grand Hotel, Târgu Mureș",
      "Petry Bistro Grill&Wine, Târgu Mureș",
      "Restaurant PRIVO, Târgu Mureș",
      "Laci csarda, Târgu Mureș",
      "La Teo Restaurant, Târgu Mureș",
      "New Chicago Restaurant, Târgu Mureș",
      "La Piazzetta, Târgu Mureș",
      "Restaurantul Lyra, Târgu Mureș",
      "B.EAT - The rhythm of food, Târgu Mureș",
      "Restaurant Casuta Bunicii, Târgu Mureș",
      "Lo Sfizio - Cucina Italiana, Târgu Mureș",
      "Thai Kitchen, Târgu Mureș",
      "Country Bread, Târgu Mureș",
      "Orobianco Ristorante, Târgu Mureș",
    ],
  },
  {
    name: "Baia Mare",
    fromArray: [
      "Gara CFR Baia Mare, Strada Gării, Baia Mare, Romania",
      "Aeroportul Internațional Maramureş Baia Mare, Tăuții-Măgherăuș, Romania",
    ],
    toArray: [
      "Aeroportul Internațional Maramureș, Baia Mare",
      "Gara Baia Mare, Baia Mare",
      "Mineralogy Museum, Baia Mare",
      "Stephen's Tower, Baia Mare",
      "COMPLEXUL ASTRONOMIC BAIA MARE, Baia Mare",
      "Baia Mare Ethnography and Folk Art Museum, Baia Mare",
      "Central Baia Mare Art Museum, Baia Mare",
      "Libertatii Square, Baia Mare",
      "VIVO! Baia Mare, Baia Mare",
      "Lacul De Acumulare Firiza, Baia Mare",
      "Petofi Sandor Museum, Baia Mare",
      "DruRelax, Baia Mare",
      "Piata Cetatii, Baia Mare",
      "Holy Trinity Catholic Church, Baia Mare",
      "Muzeul Judetean de Istorie si Arheologie, Baia Mare",
      "Centrul vechi Baia Mare, Baia Mare",
      "Hotel Castel Transilvania, Baia Mare",
      "Hotel Rivulus, Baia Mare",
      "Hotel New, Baia Mare",
      "Hotel Carpati, Baia Mare",
      "Hotel Europa, Baia Mare",
      "Eurohotel, Baia Mare",
      "Pensiunea Casa Rusu, Baia Mare",
      "Hotel Urban, Baia Mare",
      "La Fontana, Baia Mare",
      "Complex Lostrita, Baia Mare",
      "Magus Hotel, Baia Mare",
      "Hotel Diafan, Baia Mare",
      "Hotel Romanita, Baia Mare",
      "Mara Hotel, Baia Mare",
      "Pensiunea Magura, Baia Mare",
      "Camelia's Cozy Place, Baia Mare",
      "Pensiunea Ideal, Baia Mare",
      "Pensiunea Pictorilor, Baia Mare",
      "BIZO, Baia Mare",
      "PRESSCO, Baia Mare",
      "Castel Transilvania, Baia Mare",
      "Restaurant Barbarossa, Baia Mare",
      "La Palincie, Baia Mare",
      "Il Padrino, Baia Mare",
      "Casa Dobro, Baia Mare",
      "The Buffet, Baia Mare",
      "L'ancora, Baia Mare",
      "La Cucina, Baia Mare",
      "Millennium, Baia Mare",
      "Club Simared, Baia Mare",
      "Bastion, Baia Mare",
      "Philia Oazis, Baia Mare",
      "Butoiasu Cu Bere, Baia Mare",
      "Pizza Baia Mare, Baia Mare",
    ],
  },
  {
    name: "Buzău",
    fromArray: ["Gara Buzău, Bulevardul 1 Decembrie 1918, Buzău, Romania"],
    toArray: [
      "Gara Buzău, Buzău",
      "LacertA Winery, Buzău",
      "Siriu Lake, Buzău",
      "Parcul Crang, Buzău",
      "Babele de la Ulmet, Buzău",
      "Berca Mud Volcanoes, Buzău",
      "Aurora Shopping Mall, Buzău",
      "Galleria Mall, Buzău",
      "Muzeul Timpul Omului, Buzău",
      "Shopping City Buzău, Buzău",
      "Dragon Mall, Buzău",
      "Pietroasa Hotel, Buzău",
      "Avenue Hotel Buzau, Buzău",
      "Hotel Art, Buzău",
      "Hadar Chalet, Buzău",
      "Hotel Corso, Buzău",
      "Pensiune Valea Lupului, Buzău",
      "Hotel McPietroasa, Buzău",
      "Hotel Orhideea, Buzău",
      "Campus Caffe Mansion, Buzău",
      "Stejarul Buzau, Buzău",
      "The Classic, Buzău",
      "Hanul Crasmarita, Buzău",
      "Magura Hotel Complex, Buzău",
      "Pensiunea Odoba, Buzău",
      "Casa Genny, Buzău",
      "Norma Fine Wines & Dining, Buzău",
      "Garden Restaurant, Buzău",
      "O'Brothers Social Pub, Buzău",
      "Taverna Buzoiana, Buzău",
      "MORO Coffee and Juice, Buzău",
      "DACIA Romanian Fine Dining, Buzău",
      "Magnolia Urban Cafe, Buzău",
      "Oppio, Buzău",
      "Pizza Marina, Buzău",
      "Complex Moara Dragaicilor, Buzău",
      "The Lounge by Acquario, Buzău",
      "La Brasserie, Buzău",
      "Bistro Junior, Buzău",
      "Restauran New life, Buzău",
      "Art Trattoria, Buzău",
      "Tessence restaurant, Buzău",
      "Restaurant Max, Buzău",
      "Curtea Veche Buzoiana, Buzău",
      "Zigo meet&eat, Buzău",
      "Conacul Trandafirilor, Buzău",
    ],
  },
  {
    name: "Alba Iulia",
    fromArray: ["Gara CFR, Alba Iulia"],
    toArray: [
      "Gara Alba Iulia, Alba Iulia",
      "Piatra Secuiului, Alba Iulia",
      "The Citadel Alba-Carolina, Alba Iulia",
      "Ramet Monastery, Alba Iulia",
      "Muzeul Principia, Alba Iulia",
      "Palatul Apor, Alba Iulia",
      "Calcarele din Ampoița, Alba Iulia",
      "Piatra Cetii, Alba Iulia",
      "Michael the Brave Equestrian Statue, Alba Iulia",
      "Bastionul Sașilor, Alba Iulia",
      "Museikon Alba Iulia, Alba Iulia",
      "Șipote Waterfall - the bottom, Alba Iulia",
      "The Union Hall, Alba Iulia",
      "Three Fortifications Route, Alba Iulia",
      "Fortress Câlnic, Alba Iulia",
      "Lucian Blaga Memorial House, Alba Iulia",
      "Aria Naturală Protejată Iezerul Ighiel, Alba Iulia",
      "Statuia lui Lucian Blaga, Alba Iulia",
      "Batthyaneum Library, Alba Iulia",
      "Alba Mall, Alba Iulia",
      "Parcul Unirii, Alba Iulia",
      "Parc cetate, Alba Iulia",
      "Parcul Dendrologic ”Dr. Ion Vlad” Alba Iulia, Alba Iulia",
      "Parcul de Aventura Dynamis Alba Iulia, Alba Iulia",
      "Hotel Transilvania, Alba Iulia",
      "Theodora Golf Club, Alba Iulia",
      "Casa Cu Nuc, Alba Iulia",
      "Allegria Hotel, Alba Iulia",
      "La Maison de Caroline, Alba Iulia",
      "Ave Alba, Alba Iulia",
      "Marylou Pension, Alba Iulia",
      "ApartHotel Crema Residence, Alba Iulia",
      "Hotel Mariss, Alba Iulia",
      "Hotel Medieval, Alba Iulia",
      "Vila Preciosa, Alba Iulia",
      "Citadel Hostel, Alba Iulia",
      "Pensiunea Element, Alba Iulia",
      "Dante Cafe & Dine, Alba Iulia",
      "SOMM Tapas and Wine, Alba Iulia",
      "Restaurant Yiamas, Alba Iulia",
      "Gavroche - Cafe. Brasserie., Alba Iulia",
      "PUB 13, Alba Iulia",
      "La Conac, Alba Iulia",
      "La Maison de Caroline, Alba Iulia",
      "Hashtag Bistro, Alba Iulia",
      "Brothers, Alba Iulia",
      "Carpaccio, Alba Iulia",
      "Restaurant Remeny, Alba Iulia",
      "Restaurant Pizzerie DalBaffo, Alba Iulia",
    ],
  },
  {
    name: "Hunedoara",
    fromArray: ["Gara CFR Hunedoara, Piața Gării, Hunedoara"],
    toArray: [
      "Gara Hunedoara, Hunedoara",
      "Castelul Corvinilor, Hunedoara",
      "Muzeul Trenuletelor Valentin Banciu, Hunedoara",
      "Biserica Densuş, Hunedoara",
      "Gorunul Lui Horea, Hunedoara",
      "Muzeul Mineral Toda, Hunedoara",
      "Conacul Berthelot, Hunedoara",
      "Aurel Vlaicu Memorial House, Hunedoara",
      "Casa Breslelor Museum, Hunedoara",
      "Castrul Roman Micia, Hunedoara",
      "Saint Nicholas' Wooden Church, Hunedoara",
      "Complex Drum Nou, Hunedoara",
      "ZEYA Gambrinus, Hunedoara",
      "Deva Mall, Hunedoara",
      "Hostel Paltinis, Hunedoara",
      "Vila Corviniana, Hunedoara",
      "Curtea Veche Hunedoara, Hunedoara",
      "Krystal Boutique Mansion, Hunedoara",
      "Werk Hotel & Spa, Hunedoara",
      "Vila HD, Hunedoara",
      "Hotel Bulevard, Hunedoara",
      "Pensiune Stefania, Hunedoara",
      "La Fontaine, Hunedoara",
      "Gasthaus Catona, Hunedoara",
      "Restaurant WERK, Hunedoara",
      "Rustic Restaurant, Hunedoara",
      "Restaurant Bulevard, Hunedoara",
      "Pizzeria Restaurant John, Hunedoara",
      "Restaurant Unu Central, Hunedoara",
      "Popasul Castelului, Hunedoara",
      "Vintage Park Place, Hunedoara",
      "Bar Diesel, Hunedoara",
      "La Crama, Hunedoara",
      "Bulevard By Raul, Hunedoara",
      "Cafe Maranka, Hunedoara",
      "Placinta Huniadului, Hunedoara",
      "Pizzeria Viva, Hunedoara",
      "Sushi To Go, Hunedoara",
      "Cafe Bar Silver, Hunedoara",
      "Pizzeria 4 Colturi, Hunedoara",
      "Restaurant Scorpion, Hunedoara",
      "Send, Hunedoara",
      "Pizzeria Roma, Hunedoara",
      "Pizza Hot Takeaway, Hunedoara",
      "Unitech Hunedoara, Hunedoara",
      "Parcul Central, Hunedoara",
      "Parcul Tineretului, Hunedoara",
      "Parcul Corvin, Hunedoara",
    ],
  },
  {
    name: "Târgoviște",
    fromArray: ["Gară Târgoviște, Târgoviște"],
    toArray: [
      "Gara Târgoviște Nord, Târgoviște",
      "Parcul Chindia, Târgoviște",
      "Parcul Mitropoliei, Târgoviște",
      "Dâmbovița Mall, Târgoviște",
      "Muntenia Shopping Center, Târgoviște",
      "Princely Court, Târgoviște",
      "Chindiei Tower (Sunset Tower), Târgoviște",
      "Mânăstirea Dealu, Târgoviște",
      "Museum of Communism, Târgoviște",
      "Muzeul de Arta, Târgoviște",
      "Centrul Vechi Târgoviște, Târgoviște",
      "The Metropolitan Cathedral, Târgoviște",
      "Poarta Bucureștiului, Calea Domnească, Târgoviște",
      "Nova Hotel, Târgoviște",
      "Hotel Tolea, Târgoviște",
      "Hotel King, Târgoviște",
      "Casa Petru, Târgoviște",
      "Eden Guesthouse Targoviste, Târgoviște",
      "Hotel Solarino, Târgoviște",
      "Hotel Dambovita, Târgoviște",
      "Hotel Valahia, Târgoviște",
      "Pensiunea Calea Targovetilor, Târgoviște",
      "Motel Dracula, Târgoviște",
      "Guesthouse Vila Melisa, Târgoviște",
      "Edificiu Karina, Târgoviște",
      "Hotel Restaurant Dava, Târgoviște",
      "Casa Domneasca, Târgoviște",
      "Taverna Dacilor, Târgoviște",
      "Casa Veche, Târgoviște",
      "Towers Pub, Târgoviște",
      "Fragilistic Coffee Shop, Târgoviște",
      "Toscany, Târgoviște",
      "Brotacei Restaurant & Park Events, Târgoviște",
      "Urban 21, Târgoviște",
      "Xiao - Restaurant Chinezesc, Târgoviște",
      "Pizza Maestro, Târgoviște",
      "The Queen's Corner, Târgoviște",
      "Restaurant DOM, Târgoviște",
      "Story, Târgoviște",
      "Ristorante San Marco, Târgoviște",
      "Alexo, Târgoviște",
      "Real Food Sheriff, Târgoviște",
      "Belvedere Restaurant, Târgoviște",
      "Bistro Mondial, Târgoviște",
    ],
  },
  {
    name: "Satu Mare",
    fromArray: [
      "Gara Satu Mare Sud, Bulevardul Independenței, Satu Mare, Romania",
      "Aeroportul Internațional Satu Mare, Satu Mare, Romania",
    ],
    toArray: [
      "Aeroportul Internațional Satu Mare",
      "Gara Satu Mare, Satu Mare",
      "Gara Satu Mare Sud, Satu Mare",
      "Biserica reformată cu Lanturi, Satu Mare",
      "Templul Mare, Satu Mare",
      "Turnul Pompierilor, Satu Mare",
      "Palatul Administrativ, Satu Mare",
      "Teatrul de Nord, Satu Mare",
      "Statuia Lupoaicei, Satu Mare",
      "Parcul Iuliu Maniu, Satu Mare",
      "Grădina Romei, Satu Mare",
      "Parcul Liniștii, Satu Mare",
      "Parcul Cloșca, Satu Mare",
      "Parc Odobescu, Satu Mare",
      "Parcul „Dr. Fatyol Rudolf”, Satu Mare",
      "Parcul Brândușa, Satu Mare",
      "Skate Park Satu Mare, Satu Mare",
      "Parc Fitnes, Satu Mare",
      "UFO Skate Park, Satu Mare",
      "Shopping City, Satu Mare",
      "Satu Mare Shopping Plaza, Satu Mare",
      "Aushopping, Satu Mare",
      "Someșul, Satu Mare",
      "Happy Shop, Satu Mare",
      "Hotel Restaurant Perla, Satu Mare",
      "Vila Camino, Satu Mare",
      "Hotel Astoria, Satu Mare",
      "Hotel Vila Class, Satu Mare",
      "Hotel Satu Mare City, Satu Mare",
      "Hotel Melody, Satu Mare",
      "Hotel Dana, Satu Mare",
      "Charm Boutique Hotel, Satu Mare",
      "The Dome Hotel, Satu Mare",
      "Hotel President, Satu Mare",
      "Olimpia Residence District Satu Mare, Satu Mare",
      "Casa Transilvania, Satu Mare",
      "Motel Select, Satu Mare",
      "Hugo Boutique Hotel, Satu Mare",
      "Hotel Viena, Satu Mare",
      "Hotel Aramia, Satu Mare",
      "Charlietown, Satu Mare",
      "No Pardon Pub, Satu Mare",
      "Le petit Naples, Satu Mare",
      "The Dome, Satu Mare",
      "Villa Class, Satu Mare",
      "K10 Restaurant, Satu Mare",
      "Manila - Filipino Food, Satu Mare",
      "City Bistro, Satu Mare",
      "Bianco Milano, Satu Mare",
      "Restaurant Capricci, Satu Mare",
    ],
  },
  {
    name: "Sibiu",
    fromArray: [
      "Sibiu, Piața 1 Decembrie 1918, Sibiu, Romania",
      "Aeroportul Internațional Sibiu, SBZ ATCT, Șoseaua Alba Iulia, Sibiu, Romania",
    ],
    toArray: [
      "Aeroportul Internațional Sibiu, Sibiu",
      "Gara Sibiu, Sibiu",
      "Parcul Cetății, Sibiu",
      "Strada Cetății, Sibiu",
      "Muzeul de Istorie Naturală, Sibiu",
      "Turnul Dulgherilor, Sibiu",
      "Turnul Olarilor, Sibiu",
      "Aleea Nicolae Bălcescu, Sibiu",
      "Piața Mare, Sibiu",
      "Muzeu Brukenthal, Sibiu",
      "Turnul Sfatului, Sibiu",
      "Piața Mică, Sibiu",
      "Muzeul Farmaciei, Sibiu",
      "Casa Artelor, Sibiu",
      "Podul Minciunilor, Sibiu",
      "Biserica evanghelică CA Sfânta Maria, Sibiu",
      "Casa Altemberger, Sibiu",
      "Turnul Scărilor, Sibiu",
      "Muzeul de Istorie, Sibiu",
      "Muzeul de etnografie săsească Emil Sigerus, Sibiu",
      "Orașul de Jos, Sibiu",
      "Muzeul locomotivelor cu Abur, Sibiu",
      "Muzeul Astra, Sibiu",
      "Grădina Zoologică Sibiu, Sibiu",
      "Complexul de agrement Lacul lui Binder, Sibiu",
      "Baia Neptun Sibiu, Sibiu",
      "Aria Sibiu, Sibiu",
      "Parcul Natural Dumbrava Sibiului, Sibiu",
      "Piața Aurarilor, Sibiu",
      "Parcul Sub Arini, Sibiu",
      "Castelul de Lut Valea Zânelor, Sibiu",
      "MyContinental Sibiu, Sibiu",
      "Continental Forum Sibiu, Sibiu",
      "Ramada Sibiu Hotel, Sibiu",
      "Hotel Imparatul Romanilor, Sibiu",
      "Hotel Am Ring, Sibiu",
      "Hotel Apollo Central, Sibiu",
      "ART Hotel, Sibiu",
      "Hotel Marabella, Sibiu",
      "Mercure Sibiu Airport, Sibiu",
      "Hotel Stefani, Sibiu",
      "Lumos Coffee And Brunch, Sibiu",
      "Kombinat Gastro-Brewery, Sibiu",
      "Old Lisbon Sibiu, Sibiu",
      "Local, Sibiu",
      "La Cuptor, Sibiu",
      "Benjamin Steakhouse & Bar, Sibiu",
      "Hochmeister Delikat'essen, Sibiu",
      "Crama Sibiul Vechi, Sibiu",
      "Jacob Grillhouse, Sibiu",
    ],
  },
];
